### PR TITLE
Bug exclamation point inflation

### PR DESCRIPTION
**Pull request by jduffy3**
This PR fixes issue with `!!!` keyword not being triggered.

### Root Cause:

The regex `\b(' + keyword + ')\b` does not catch punctuation because `\b` is a word boundary.

In order to catch it this needs to be `\B` rather than `\b` at the end.

I defined the new keyword as ` "keyword": "!{3,}",` because this will catch three or more exclamations versus just three. There does seem to be a bit of regex inserted into other phrases in WarningMessages.json (in fact there was another keyword not being picked up because there was a space inserted) so thought adding the quantifier shouldn't be too much. Maybe later on we just want the keyword to be a pure regex string rather than wrapping it?

### CODE REVIEW

**Comment by sbrudz** [comment]
I love how you've refactored in small increments.  Nice work!

One side-effect of separating out the punctuation warnings is that `!!!` is no longer included in the table in the options panel:

image

It would be great to have it added back in.  (see options/options.ejs and webpack.config.js for how they're wired together)

**Comment by jduffy3** [comment]
@sbrudz took a while to think about it, but the best approach I could come up with is to add an extra field `displayLabel` otherwise it would've displayed the phrase as `!{3,}` 😆 

was able to inline some ejs stuff as well. Let me know what you think :)

**Review by sbrudz — COMMENTED** [review]
Overall, it looks good and works properly.  

The warning files are now in two places, though.  It would be good to delete one set of files to prevent confusion.  

Also, what's the difference between the phrases file and the punctuations file?  It would be good to have a note in the ReadMe that provides guidance on which file to use for different situations.  Or maybe with the addition of displayLabel, does the information still need to be split into separate files?

**Comment by jduffy3** [comment]
Nice catch!

Good points you're making. The intention behind it was that we use specific regex matches for phrases and punctuation, really its the wrapper `\b (keyword) \b` for phrases and `\b (keyword) \B` for punctuation.

What do you think of moving the entire regex pattern into the json file then we can have just one file and avoid it altogether?

**Comment by sbrudz** [comment]
That sounds great.  Maybe we should call the field "pattern" instead of "keyword"?

**Review by sbrudz — COMMENTED** [review]
The switch to using separate regex's and display labels looks great and works well.

While testing, I did find some edge cases for the `!!!` warning where it doesn't work.  For example, if there's a newline after the `!!!` the warning for it doesn't show up:
image
It works fine if there's a space after the `!!!`.

**Comment by sbrudz** [comment]
What if we removed the boundaries so that `!!!` always triggered the warning?

**Comment by jduffy3** [comment]
It increases the scope of the pattern but fixes the issue you found! Delivered!

**Review by sbrudz — APPROVED** [review]
Looks good!  Thank you!

**Pull request merged**
